#!/usr/bin/python3
from PIL import Image, ImageDraw, ImageFont
import gi
gi.require_version('Gtk', '3.0')
from dotenv import get_key
from os import system, getlogin
from gi.repository import Playerctl, GLib
import lyricsgenius
from random import randint
from imp import load_source
conf = load_source('config', f'/home/{getlogin()}/.config/walyrics/config.py')

system('clear')
apikey = get_key(dotenv_path=conf.envpath, key_to_get="GENIUS_APIKEY")
genius = lyricsgenius.Genius(apikey)
player = Playerctl.Player()

prev_song = ''

def on_metadata(player, metadata):
    global prev_song
    global conf
    try:
        image = Image.open(conf.wallpaper)
    except FileNotFoundError:
        system(f'notify-send "Wallpaper {conf.wallpaper} not found. Is it a path mistake??"') 
        exit(1)
    if 'xesam:artist' in metadata.keys() and 'xesam:title' in metadata.keys() and metadata['xesam:title'] != prev_song:
        prev_song = metadata['xesam:title']
        song = genius.search_song(metadata['xesam:title'], metadata['xesam:artist'][0])
        try:
            lyrics = song.lyrics
        except AttributeError:
            lyrics = f"Cannot fetch {metadata['xesam:title']}'s lyrics... It is probably because of it has not been added to Genius Lyrics's list yet."

        draw = ImageDraw.Draw(image)
        prev_lyrics = lyrics
        
        draw.text((conf.offset_x, conf.offset_y), lyrics, font=ImageFont.truetype(conf.fontpath, conf.fontsize), fill=conf.fontcolor ,align='left')

        fname = randint(1,conf.randlimit)
        system('rm /tmp/walyrics*.png')
        image.save(f'/tmp/walyrics{fname}.png')
        system(f'feh --bg-fill /tmp/walyrics{fname}.png')
        print('wallpaper set')

player.connect('metadata', on_metadata)

main = GLib.MainLoop()
main.run()
